Recipe.create([{ name: 'Roti', instructions: 'Roti making instructions ', cooking_time: 30 },
  { name: 'Pulav', instructions: 'Pulav Making instructions', cooking_time: 20 },
  { name: 'Paratha', instructions: 'Paratha Making instructions', cooking_time: 40 },
  { name: 'Paneer Bhurji', instructions: 'Paneer Bhurji Making instructions', cooking_time: 45 },
  { name: 'Kaju Kari', instructions: 'Kaju kari Making instructions', cooking_time: 60 },
  { name: 'Mix Veg Subji', instructions: 'Mix Veg Sabji Making instructions', cooking_time: 35 },
  { name: 'Masala Tea', instructions: 'Masala Tea Making instructions', cooking_time: 10 },
 ])


Ingredient.create([{ name: 'Wheat Flour' },
       { name: 'Salt' },
       { name: 'Sugar' },
       { name: 'Oil' },
       { name: 'Cheeze' },
       { name: 'Butter' },
       { name: 'Coriander Powder' },
       { name: 'Paneer' },
       { name: 'Kashew' },
       { name: 'Chilli Powder' },
       { name: 'Cumins' },
       { name: 'Rice' },
       { name: 'Potato' },
       { name: 'Tomato' },
       { name: 'Onion' },
       { name: 'Bringel' },
       { name: 'Tea' },
       { name: 'Milk' },
     ])

RecipeIngredient.create([{ recipe_id: 1, ingredient_id: 1 },
            { recipe_id: 1, ingredient_id: 2 },
            { recipe_id: 2, ingredient_id: 12 },
            { recipe_id: 2, ingredient_id: 2 },
            { recipe_id: 2, ingredient_id: 9 },
            { recipe_id: 2, ingredient_id: 6 },
            { recipe_id: 3, ingredient_id: 1 },
            { recipe_id: 3, ingredient_id: 2 },
            { recipe_id: 3, ingredient_id: 5 },
            { recipe_id: 4, ingredient_id: 4 },
            { recipe_id: 4, ingredient_id: 7 },
            { recipe_id: 4, ingredient_id: 8 },
            { recipe_id: 4, ingredient_id: 10 },
            { recipe_id: 4, ingredient_id: 14 },
            { recipe_id: 4, ingredient_id: 15 },
            { recipe_id: 5, ingredient_id: 6 },
            { recipe_id: 5, ingredient_id: 5 },
            { recipe_id: 5, ingredient_id: 7 },
            { recipe_id: 5, ingredient_id: 4 },
            { recipe_id: 5, ingredient_id: 9 },
            { recipe_id: 5, ingredient_id: 10 },
            { recipe_id: 5, ingredient_id: 14 },
            { recipe_id: 5, ingredient_id: 15 },
            { recipe_id: 6, ingredient_id: 13 },
            { recipe_id: 6, ingredient_id: 14 },
            { recipe_id: 6, ingredient_id: 15 },
            { recipe_id: 6, ingredient_id: 16 },
            { recipe_id: 6, ingredient_id: 4 },
            { recipe_id: 6, ingredient_id: 6 },
            { recipe_id: 6, ingredient_id: 7 },
            { recipe_id: 6, ingredient_id: 10 },
            { recipe_id: 7, ingredient_id: 17 },
            { recipe_id: 7, ingredient_id: 18 },
            { recipe_id: 7, ingredient_id: 3 },
           ])